name: flutter_keyboard_visibility
description: A Flutter plugin for detecting keyboard visibility changes across platforms.
version: 5.4.1
homepage: https://github.com/adee42/flutter_keyboard_visibility

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_keyboard_visibility
        pluginClass: FlutterKeyboardVisibilityPlugin
      ios:
        pluginClass: FlutterKeyboardVisibilityPlugin
      web:
        pluginClass: FlutterKeyboardVisibilityPlugin
        fileName: flutter_keyboard_visibility_web.dart 